APT::FTPArchive::Release {
  Origin "JAEA Naohito Sakamoto";
  Label "pbvr";
  Suite "stable";
  Codename "stable";
  Architectures "amd64";
  Components "main";
  Description "pbvr APT repository";
};
